kakao:
  key: [INPUT_KAKAO_REST_API_KEY]

spring:
  datasource:
    url: jdbc:mysql://[INPUT_localhost&IP]:[PORT]/[DB_NAME]?serverTimezone=Asia/Seoul
    username: [INPUT_DB_USERNAME]
    password: [INPUT_DB_PW] # 특수문자가 포함된 경우 따옴표로 감싸는 것이 안전합니다.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNlY3JldC1rZXktbmVlZHMtdG8tYmUtbG9uZy1lbm91Z2g= # 사용할 비밀 키 (임의의 긴 문자열)
  expiration: 86400000 # 24시간 (밀리초 단위)
